package cn.viviant.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import cn.viviant.bean.Level;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LEVEL.
*/
public class LevelDao extends AbstractDao<Level, Long> {

    public static final String TABLENAME = "LEVEL";

    /**
     * Properties of entity Level.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LevelName = new Property(1, String.class, "levelName", false, "LEVEL_NAME");
        public final static Property LevelDescription = new Property(2, String.class, "levelDescription", false, "LEVEL_DESCRIPTION");
        public final static Property Color = new Property(3, String.class, "color", false, "COLOR");
        public final static Property LevelNum = new Property(4, Integer.class, "levelNum", false, "LEVEL_NUM");
        public final static Property State = new Property(5, Integer.class, "state", false, "STATE");
    };


    public LevelDao(DaoConfig config) {
        super(config);
    }
    
    public LevelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LEVEL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'LEVEL_NAME' TEXT NOT NULL ," + // 1: levelName
                "'LEVEL_DESCRIPTION' TEXT NOT NULL ," + // 2: levelDescription
                "'COLOR' TEXT," + // 3: color
                "'LEVEL_NUM' INTEGER," + // 4: levelNum
                "'STATE' INTEGER);"); // 5: state
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LEVEL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Level entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getLevelName());
        stmt.bindString(3, entity.getLevelDescription());
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(4, color);
        }
 
        Integer levelNum = entity.getLevelNum();
        if (levelNum != null) {
            stmt.bindLong(5, levelNum);
        }
 
        Integer state = entity.getState();
        if (state != null) {
            stmt.bindLong(6, state);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Level readEntity(Cursor cursor, int offset) {
        Level entity = new Level( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // levelName
            cursor.getString(offset + 2), // levelDescription
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // color
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // levelNum
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // state
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Level entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLevelName(cursor.getString(offset + 1));
        entity.setLevelDescription(cursor.getString(offset + 2));
        entity.setColor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLevelNum(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setState(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Level entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Level entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
