package cn.viviant.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LEVEL.
 */
public class Level {

    private Long id;
    /** Not-null value. */
    private String levelName;
    /** Not-null value. */
    private String levelDescription;
    private String color;
    private Integer levelNum;
    private Integer state;

    public Level() {
    }

    public Level(Long id) {
        this.id = id;
    }

    public Level(Long id, String levelName, String levelDescription, String color, Integer levelNum, Integer state) {
        this.id = id;
        this.levelName = levelName;
        this.levelDescription = levelDescription;
        this.color = color;
        this.levelNum = levelNum;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLevelName() {
        return levelName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    /** Not-null value. */
    public String getLevelDescription() {
        return levelDescription;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLevelDescription(String levelDescription) {
        this.levelDescription = levelDescription;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Integer getLevelNum() {
        return levelNum;
    }

    public void setLevelNum(Integer levelNum) {
        this.levelNum = levelNum;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
