package cn.viviant.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLANTHING.
 */
public class Planthing {

    private Long id;
    /** Not-null value. */
    private String planthingName;
    private String planthingDescription;
    /** Not-null value. */
    private String doDateTime;
    private String planThingPlace;
    private Boolean flagRemind;
    private String remindDate;
    private Integer state;

    public Planthing() {
    }

    public Planthing(Long id) {
        this.id = id;
    }

    public Planthing(Long id, String planthingName, String planthingDescription, String doDateTime, String planThingPlace, Boolean flagRemind, String remindDate, Integer state) {
        this.id = id;
        this.planthingName = planthingName;
        this.planthingDescription = planthingDescription;
        this.doDateTime = doDateTime;
        this.planThingPlace = planThingPlace;
        this.flagRemind = flagRemind;
        this.remindDate = remindDate;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPlanthingName() {
        return planthingName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanthingName(String planthingName) {
        this.planthingName = planthingName;
    }

    public String getPlanthingDescription() {
        return planthingDescription;
    }

    public void setPlanthingDescription(String planthingDescription) {
        this.planthingDescription = planthingDescription;
    }

    /** Not-null value. */
    public String getDoDateTime() {
        return doDateTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDoDateTime(String doDateTime) {
        this.doDateTime = doDateTime;
    }

    public String getPlanThingPlace() {
        return planThingPlace;
    }

    public void setPlanThingPlace(String planThingPlace) {
        this.planThingPlace = planThingPlace;
    }

    public Boolean getFlagRemind() {
        return flagRemind;
    }

    public void setFlagRemind(Boolean flagRemind) {
        this.flagRemind = flagRemind;
    }

    public String getRemindDate() {
        return remindDate;
    }

    public void setRemindDate(String remindDate) {
        this.remindDate = remindDate;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
