package cn.viviant.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import cn.viviant.bean.Planthing;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PLANTHING.
*/
public class PlanthingDao extends AbstractDao<Planthing, Long> {

    public static final String TABLENAME = "PLANTHING";

    /**
     * Properties of entity Planthing.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PlanthingName = new Property(1, String.class, "planthingName", false, "PLANTHING_NAME");
        public final static Property PlanthingDescription = new Property(2, String.class, "planthingDescription", false, "PLANTHING_DESCRIPTION");
        public final static Property DoDateTime = new Property(3, String.class, "doDateTime", false, "DO_DATE_TIME");
        public final static Property PlanThingPlace = new Property(4, String.class, "planThingPlace", false, "PLAN_THING_PLACE");
        public final static Property FlagRemind = new Property(5, Boolean.class, "flagRemind", false, "FLAG_REMIND");
        public final static Property RemindDate = new Property(6, String.class, "remindDate", false, "REMIND_DATE");
        public final static Property State = new Property(7, Integer.class, "state", false, "STATE");
    };


    public PlanthingDao(DaoConfig config) {
        super(config);
    }
    
    public PlanthingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PLANTHING' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PLANTHING_NAME' TEXT NOT NULL ," + // 1: planthingName
                "'PLANTHING_DESCRIPTION' TEXT," + // 2: planthingDescription
                "'DO_DATE_TIME' TEXT NOT NULL ," + // 3: doDateTime
                "'PLAN_THING_PLACE' TEXT," + // 4: planThingPlace
                "'FLAG_REMIND' INTEGER," + // 5: flagRemind
                "'REMIND_DATE' TEXT," + // 6: remindDate
                "'STATE' INTEGER);"); // 7: state
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PLANTHING'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Planthing entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPlanthingName());
 
        String planthingDescription = entity.getPlanthingDescription();
        if (planthingDescription != null) {
            stmt.bindString(3, planthingDescription);
        }
        stmt.bindString(4, entity.getDoDateTime());
 
        String planThingPlace = entity.getPlanThingPlace();
        if (planThingPlace != null) {
            stmt.bindString(5, planThingPlace);
        }
 
        Boolean flagRemind = entity.getFlagRemind();
        if (flagRemind != null) {
            stmt.bindLong(6, flagRemind ? 1l: 0l);
        }
 
        String remindDate = entity.getRemindDate();
        if (remindDate != null) {
            stmt.bindString(7, remindDate);
        }
 
        Integer state = entity.getState();
        if (state != null) {
            stmt.bindLong(8, state);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Planthing readEntity(Cursor cursor, int offset) {
        Planthing entity = new Planthing( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // planthingName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // planthingDescription
            cursor.getString(offset + 3), // doDateTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // planThingPlace
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // flagRemind
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // remindDate
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // state
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Planthing entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPlanthingName(cursor.getString(offset + 1));
        entity.setPlanthingDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDoDateTime(cursor.getString(offset + 3));
        entity.setPlanThingPlace(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFlagRemind(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setRemindDate(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setState(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Planthing entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Planthing entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
