package cn.viviant.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ROLE.
 */
public class Role {

    private Long id;
    /** Not-null value. */
    private String roleName;
    /** Not-null value. */
    private String establishDate;
    private String roleDescription;
    private Boolean flagAvailiable;
    private Integer state;

    public Role() {
    }

    public Role(Long id) {
        this.id = id;
    }

    public Role(Long id, String roleName, String establishDate, String roleDescription, Boolean flagAvailiable, Integer state) {
        this.id = id;
        this.roleName = roleName;
        this.establishDate = establishDate;
        this.roleDescription = roleDescription;
        this.flagAvailiable = flagAvailiable;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRoleName() {
        return roleName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /** Not-null value. */
    public String getEstablishDate() {
        return establishDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEstablishDate(String establishDate) {
        this.establishDate = establishDate;
    }

    public String getRoleDescription() {
        return roleDescription;
    }

    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }

    public Boolean getFlagAvailiable() {
        return flagAvailiable;
    }

    public void setFlagAvailiable(Boolean flagAvailiable) {
        this.flagAvailiable = flagAvailiable;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
