package cn.viviant.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TAG.
 */
public class Tag {

    private Long id;
    /** Not-null value. */
    private String tagName;
    /** Not-null value. */
    private String establishDate;
    private String tagDescription;
    private Boolean flagAvailiable;
    private Integer state;

    public Tag() {
    }

    public Tag(Long id) {
        this.id = id;
    }

    public Tag(Long id, String tagName, String establishDate, String tagDescription, Boolean flagAvailiable, Integer state) {
        this.id = id;
        this.tagName = tagName;
        this.establishDate = establishDate;
        this.tagDescription = tagDescription;
        this.flagAvailiable = flagAvailiable;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTagName() {
        return tagName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /** Not-null value. */
    public String getEstablishDate() {
        return establishDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEstablishDate(String establishDate) {
        this.establishDate = establishDate;
    }

    public String getTagDescription() {
        return tagDescription;
    }

    public void setTagDescription(String tagDescription) {
        this.tagDescription = tagDescription;
    }

    public Boolean getFlagAvailiable() {
        return flagAvailiable;
    }

    public void setFlagAvailiable(Boolean flagAvailiable) {
        this.flagAvailiable = flagAvailiable;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
