package cn.viviant.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USERINFO.
 */
public class Userinfo {

    private Long id;
    /** Not-null value. */
    private String username;
    private String sex;
    private String userEmail;
    private String userImage;
    private String registerDate;
    private Boolean flagVip;
    private Boolean flagLogout;
    private Integer state;
    private String telphone;
    private String address;

    public Userinfo() {
    }

    public Userinfo(Long id) {
        this.id = id;
    }

    public Userinfo(Long id, String username, String sex, String userEmail, String userImage, String registerDate, Boolean flagVip, Boolean flagLogout, Integer state, String telphone, String address) {
        this.id = id;
        this.username = username;
        this.sex = sex;
        this.userEmail = userEmail;
        this.userImage = userImage;
        this.registerDate = registerDate;
        this.flagVip = flagVip;
        this.flagLogout = flagLogout;
        this.state = state;
        this.telphone = telphone;
        this.address = address;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserImage() {
        return userImage;
    }

    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }

    public String getRegisterDate() {
        return registerDate;
    }

    public void setRegisterDate(String registerDate) {
        this.registerDate = registerDate;
    }

    public Boolean getFlagVip() {
        return flagVip;
    }

    public void setFlagVip(Boolean flagVip) {
        this.flagVip = flagVip;
    }

    public Boolean getFlagLogout() {
        return flagLogout;
    }

    public void setFlagLogout(Boolean flagLogout) {
        this.flagLogout = flagLogout;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getTelphone() {
        return telphone;
    }

    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

}
