package viviant.cn.weeklyplan.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import viviant.cn.weeklyplan.bean.Userinfo;
import viviant.cn.weeklyplan.bean.Tag;
import viviant.cn.weeklyplan.bean.Role;
import viviant.cn.weeklyplan.bean.Level;
import viviant.cn.weeklyplan.bean.Planthing;

import viviant.cn.weeklyplan.bean.UserinfoDao;
import viviant.cn.weeklyplan.bean.TagDao;
import viviant.cn.weeklyplan.bean.RoleDao;
import viviant.cn.weeklyplan.bean.LevelDao;
import viviant.cn.weeklyplan.bean.PlanthingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userinfoDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig roleDaoConfig;
    private final DaoConfig levelDaoConfig;
    private final DaoConfig planthingDaoConfig;

    private final UserinfoDao userinfoDao;
    private final TagDao tagDao;
    private final RoleDao roleDao;
    private final LevelDao levelDao;
    private final PlanthingDao planthingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userinfoDaoConfig = daoConfigMap.get(UserinfoDao.class).clone();
        userinfoDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        roleDaoConfig = daoConfigMap.get(RoleDao.class).clone();
        roleDaoConfig.initIdentityScope(type);

        levelDaoConfig = daoConfigMap.get(LevelDao.class).clone();
        levelDaoConfig.initIdentityScope(type);

        planthingDaoConfig = daoConfigMap.get(PlanthingDao.class).clone();
        planthingDaoConfig.initIdentityScope(type);

        userinfoDao = new UserinfoDao(userinfoDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        roleDao = new RoleDao(roleDaoConfig, this);
        levelDao = new LevelDao(levelDaoConfig, this);
        planthingDao = new PlanthingDao(planthingDaoConfig, this);

        registerDao(Userinfo.class, userinfoDao);
        registerDao(Tag.class, tagDao);
        registerDao(Role.class, roleDao);
        registerDao(Level.class, levelDao);
        registerDao(Planthing.class, planthingDao);
    }
    
    public void clear() {
        userinfoDaoConfig.getIdentityScope().clear();
        tagDaoConfig.getIdentityScope().clear();
        roleDaoConfig.getIdentityScope().clear();
        levelDaoConfig.getIdentityScope().clear();
        planthingDaoConfig.getIdentityScope().clear();
    }

    public UserinfoDao getUserinfoDao() {
        return userinfoDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public RoleDao getRoleDao() {
        return roleDao;
    }

    public LevelDao getLevelDao() {
        return levelDao;
    }

    public PlanthingDao getPlanthingDao() {
        return planthingDao;
    }

}
