package viviant.cn.weeklyplan.bean;

import java.io.Serializable;
import java.util.List;
import viviant.cn.weeklyplan.bean.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LEVEL.
 */
public class Level implements Serializable{

    private Long id;
    /** Not-null value. */
    private String levelName;
    /** Not-null value. */
    private String levelDescription;
    private String color;
    private Integer levelNum;
    private Integer state;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient LevelDao myDao;

    private List<Planthing> planthings;

    @Override
    public String toString() { //为什么要重写toString()呢？因为适配器在显示数据的时候，如果传入适配器的对象不是字符串的情况下，直接就使用对象.toString()
        // TODO Auto-generated method stub
        return levelName;
    }

    public Level() {
    }

    public Level(Long id) {
        this.id = id;
    }

    public Level(Long id, String levelName, String levelDescription, String color, Integer levelNum, Integer state) {
        this.id = id;
        this.levelName = levelName;
        this.levelDescription = levelDescription;
        this.color = color;
        this.levelNum = levelNum;
        this.state = state;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLevelDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLevelName() {
        return levelName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    /** Not-null value. */
    public String getLevelDescription() {
        return levelDescription;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLevelDescription(String levelDescription) {
        this.levelDescription = levelDescription;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Integer getLevelNum() {
        return levelNum;
    }

    public void setLevelNum(Integer levelNum) {
        this.levelNum = levelNum;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Planthing> getPlanthings() {
        if (planthings == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PlanthingDao targetDao = daoSession.getPlanthingDao();
            List<Planthing> planthingsNew = targetDao._queryLevel_Planthings(id);
            synchronized (this) {
                if(planthings == null) {
                    planthings = planthingsNew;
                }
            }
        }
        return planthings;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetPlanthings() {
        planthings = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
