package viviant.cn.weeklyplan.bean;

import java.util.List;
import viviant.cn.weeklyplan.bean.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TAG.
 */
public class Tag {

    private Long id;
    /** Not-null value. */
    private String tagName;
    /** Not-null value. */
    private String establishDate;
    private String tagDescription;
    private Boolean flagAvailiable;
    private Integer state;
    private long userinfoTId;
    private Long planthingId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TagDao myDao;

    private List<Planthing> planthings;

    public Tag() {
    }

    public Tag(Long id) {
        this.id = id;
    }

    public Tag(Long id, String tagName, String establishDate, String tagDescription, Boolean flagAvailiable, Integer state, long userinfoTId, Long planthingId) {
        this.id = id;
        this.tagName = tagName;
        this.establishDate = establishDate;
        this.tagDescription = tagDescription;
        this.flagAvailiable = flagAvailiable;
        this.state = state;
        this.userinfoTId = userinfoTId;
        this.planthingId = planthingId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTagDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTagName() {
        return tagName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /** Not-null value. */
    public String getEstablishDate() {
        return establishDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEstablishDate(String establishDate) {
        this.establishDate = establishDate;
    }

    public String getTagDescription() {
        return tagDescription;
    }

    public void setTagDescription(String tagDescription) {
        this.tagDescription = tagDescription;
    }

    public Boolean getFlagAvailiable() {
        return flagAvailiable;
    }

    public void setFlagAvailiable(Boolean flagAvailiable) {
        this.flagAvailiable = flagAvailiable;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public long getUserinfoTId() {
        return userinfoTId;
    }

    public void setUserinfoTId(long userinfoTId) {
        this.userinfoTId = userinfoTId;
    }

    public Long getPlanthingId() {
        return planthingId;
    }

    public void setPlanthingId(Long planthingId) {
        this.planthingId = planthingId;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Planthing> getPlanthings() {
        if (planthings == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PlanthingDao targetDao = daoSession.getPlanthingDao();
            List<Planthing> planthingsNew = targetDao._queryTag_Planthings(id);
            synchronized (this) {
                if(planthings == null) {
                    planthings = planthingsNew;
                }
            }
        }
        return planthings;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetPlanthings() {
        planthings = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
